DebugMode: false
Positions:
  test:
    enable: true
    ShowType:
      StartStop: title
      Time: chat
      Rank: chat
    Start:
      World: world
      X: 0.0
      Y: 0.0
      Z: 0.0
    End:
      World: world
      X: 0.0
      Y: 0.0
      Z: 0.0
    PlayerTime:
      player_uuid: duration
ExceptPlayers:
 - player_uuid