name: PositionTimer
main: com.github.smk7758.PositionTimerForOld.Main
version: 0.0.1
author: smk7758
permissions:
commands:
  PositionTimer:
    description: PositionTimer's command.
    aliases: [position, point, p]